services:
  db:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: experts
      MYSQL_USER: sample
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
